"""empty message

Revision ID: 258c86cb4e8d
Revises: 4a7e3081782e
Create Date: 2025-11-30 17:40:06.905024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258c86cb4e8d'
down_revision = '4a7e3081782e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id_pk'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'pokemon_id', name='uq_favorite_trainer_pokemon')
    )
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_pokemon_id'), ['pokemon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_trainer_id'), ['trainer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_favorite_pokemon_id'))

    op.drop_table('favorite')
    # ### end Alembic commands ###
