"""empty message

Revision ID: 4a7e3081782e
Revises: a0ea76bd5dca
Create Date: 2025-11-30 00:46:17.945793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7e3081782e'
down_revision = 'a0ea76bd5dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('type_id', sa.Integer(), nullable=True),
                    sa.Column('damage_class', sa.String(
                        length=20), nullable=True),
                    sa.Column('power', sa.Integer(), nullable=True),
                    sa.Column('accuracy', sa.Integer(), nullable=True),
                    sa.Column('pp', sa.Integer(), nullable=True),
                    sa.Column('priority', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.CheckConstraint(
                        'accuracy BETWEEN 0 AND 100 OR accuracy IS NULL', name='ck_move_accuracy_range'),
                    sa.CheckConstraint('power >=0 OR power IS NULL',
                                       name='ck_move_power_non_negative'),
                    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('move', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_move_type_id'), [
                              'type_id'], unique=False)

    op.create_table('pokemon_move',
                    sa.Column('pokemon_id', sa.Integer(), nullable=False),
                    sa.Column('move_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['move_id'], ['move.id'], ),
                    sa.ForeignKeyConstraint(
                        ['pokemon_id'], ['pokemon.id_pk'], ),
                    sa.PrimaryKeyConstraint('pokemon_id', 'move_id')
                    )
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Numeric(
            precision=4, scale=1), nullable=True))
        batch_op.drop_column('heigth')

    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('introduced_in_generation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.drop_column('introduced_in_generation')

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heigth', sa.NUMERIC(
            precision=4, scale=1), autoincrement=False, nullable=True))
        batch_op.drop_column('height')

    op.drop_table('pokemon_move')
    with op.batch_alter_table('move', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_move_type_id'))

    op.drop_table('move')
    # ### end Alembic commands ###
