"""ampliar longitud de password hash

Revision ID: 660ce7c5824f
Revises: 159b4758af82
Create Date: 2025-11-19 17:28:50.981075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660ce7c5824f'
down_revision = '159b4758af82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=225),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
