"""empty message

Revision ID: a0ea76bd5dca
Revises: bf2cbf35595c
Create Date: 2025-11-25 23:11:48.253670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ea76bd5dca'
down_revision = 'bf2cbf35595c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('short_effect', sa.String(length=225), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('is_hidden_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemon_ability',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['ability.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id_pk'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'ability_id')
    )
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heigth', sa.Numeric(precision=4, scale=1), nullable=True))
        batch_op.drop_column('height')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True))
        batch_op.drop_column('heigth')

    op.drop_table('pokemon_ability')
    op.drop_table('ability')
    # ### end Alembic commands ###
