"""empty message

Revision ID: bf2cbf35595c
Revises: 660ce7c5824f
Create Date: 2025-11-25 20:53:32.244384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2cbf35595c'
down_revision = '660ce7c5824f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id_pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pokedex_number', sa.Integer(), nullable=False),
    sa.Column('height', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('id_pk'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pokedex_number')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_type_name')
    )
    op.create_table('pokemon_type',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id_pk'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'type_id')
    )
    with op.batch_alter_table('trainer') as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))

    op.execute(sa.text("UPDATE trainer SET created_at = NOW() WHERE created_at IS NULL"))

    with op.batch_alter_table("trainer") as batch_op:
        batch_op.alter_column("created_at", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('created_at')

    op.drop_table('pokemon_type')
    op.drop_table('type')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
