base_types = [
            ("Normal", 1),
            ("Fuego", 1),
            ("Agua", 1),
            ("Electrico", 1),
            ("Planta", 1),
            ("Hielo", 1),
            ("Lucha", 1),
            ("Lucha", 1),
            ("Veneno", 1),
            ("Tierra", 1),
            ("Volador", 1),
            ("Psíquico", 1),
            ("Bicho", 1),
            ("Roca", 1),
            ("Fantasma", 1),
            ("Dragón", 1),
            ("Oscuro", 2),
            ("Acero", 2),
            ("Hada", 6),
        ]